In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../Traffic_Violations.csv")
data.head(5)

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
0,52282e8c-f2e1-4bb5-8509-2d5e4f8da8ca,05/01/2023,23:11:00,MCP,"3rd District, Silver Spring",OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.00000,No,...,13-401(b1),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(0.0, 0.0)"
1,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,16-101(a1),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
2,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,13-409(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
3,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,21-310(a),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"
4,b66f253b-af29-4bc4-bb73-93755ca2a779,08/31/2023,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.15301,No,...,21-801(b),Transportation Article,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)"

In [3]:
data.describe()

           Latitude     Longitude          Year
count  2.070115e+06  2.070115e+06  2.059470e+06
mean   3.613803e+01 -7.130162e+01  2.007615e+03
std    1.032062e+01  2.036307e+01  8.489762e+01
min    0.000000e+00 -1.512560e+02  0.000000e+00
25%    3.901642e+01 -7.719294e+01  2.003000e+03
50%    3.906618e+01 -7.708753e+01  2.008000e+03
75%    3.913717e+01 -7.702696e+01  2.013000e+03
max    4.154316e+01  3.906444e+01  9.999000e+03

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 2070115 entries, 0 to 2070114
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   SeqID                    str
 1   Date Of Stop             str
 2   Time Of Stop             str
 3   Agency                   str
 4   SubAgency                str
 5   Description              str
 6   Location                 str
 7   Latitude                 float64
 8   Longitude                float64
 9   Accident                 str
 10  Belts                    str
 11  Personal Injury          str
 12  Property Damage          str
 13  Fatal                    str
 14  Commercial License       str
 15  HAZMAT                   str
 16  Commercial Vehicle       str
 17  Alcohol                  str
 18  Work Zone                str
 19  Search Conducted         str
 20  Search Disposition       str
 21  Search Outcome           str
 22  Search Reason            str
 23  Search Reason For Stop   str
 24  Search Type              str
 25  Search Arrest Reason     str
 26  State                    str
 27  VehicleType              str
 28  Year                     float64
 29  Make                     str
 30  Model                    str
 31  Color                    str
 32  Violation Type           str
 33  Charge                   str
 34  Article                  str
 35  Contributed To Accident  bool
 36  Race                     str
 37  Gender                   str
 38  Driver City              str
 39  Driver State             str
 40  DL State                 str
 41  Arrest Type              str
 42  Geolocation              str
dtypes: bool(1), float64(3), str(39)
memory usage: 1.3 GB

In [5]:
data.isnull().sum().sort_values(ascending=False)

Search Arrest Reason       2008149
Search Type                1980582
Search Reason              1980574
Search Disposition         1980574
Search Outcome              805416
Search Reason For Stop      786428
Search Conducted            786125
Article                      92680
Color                        22300
Year                         10645
DL State                       929
Driver City                    519
Model                          223
Make                            74
State                           59
Driver State                    11
Description                     10
Location                         4
VehicleType                      0
Violation Type                   0
Contributed To Accident          0
Race                             0
Arrest Type                      0
Gender                           0
Charge                           0
SeqID                            0
Date Of Stop                     0
Belts                            0
Time Of Stop                     0
Agency                           0
SubAgency                        0
Latitude                         0
Longitude                        0
Accident                         0
Personal Injury                  0
Work Zone                        0
Property Damage                  0
Fatal                            0
Commercial License               0
HAZMAT                           0
Commercial Vehicle               0
Alcohol                          0
Geolocation                      0
dtype: int64

In [6]:
data.describe(include="object")

C:\Users\Akshaya\AppData\Local\Temp\ipykernel_5728\460854327.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  data.describe(include="object")

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Accident,Belts,Personal Injury,...,Violation Type,Charge,Article,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
count,2070115,2070115,2070115,2070115,2070115,2070105,2070111,2070115,2070115,2070115,...,2070115,2070115,1977435,2070115,2070115,2069596,2070104,2069186,2070115,2070115
unique,1178080,5086,1440,1,9,17806,269352,2,2,2,...,4,1199,6,6,3,9374,68,72,19,1026161
top,33c49de3-9e36-4f36-9326-b59a95e86fe8,03/17/2015,23:30:00,MCP,"4th District, Wheaton",DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC...,MONTGOMERY VILLAGE AVE @ RUSSELL AVE,No,No,No,...,Warning,21-801.1,Transportation Article,WHITE,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(0.0, 0.0)"
freq,59,1281,3000,2070115,449193,171401,2451,2013432,2005748,2044929,...,1090515,286707,1957419,691032,1393963,503076,1871813,1805484,1657617,156092

# Handling Duplicate Values:

In [7]:
data["SeqID"].duplicated().sum()

892035

In [8]:
(data.duplicated().sum()/len(data))*100

0.11371348934721018

Here, the duplicate rows accounts for only 0.11% of the total rows. Therefore removing them.

In [9]:
data[data.duplicated(keep=False)].sort_values("SeqID").head(20)

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Charge,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation
751900,001993a8-c78a-4db9-b631-1f38b4908983,08/18/2018,17:36:00,MCP,"5th District, Germantown",KNOWINGLY DRIVING UNINSURED VEHICLE,21030 FREDERICK ROAD,39.201738,-77.247197,No,...,17-107(a1),Transportation Article,False,WHITE,M,GERMANTOWN,MD,MD,A - Marked Patrol,"(39.2017383333333, -77.2471966666667)"
758447,001993a8-c78a-4db9-b631-1f38b4908983,08/18/2018,17:36:00,MCP,"5th District, Germantown",KNOWINGLY DRIVING UNINSURED VEHICLE,21030 FREDERICK ROAD,39.201738,-77.247197,No,...,17-107(a1),Transportation Article,False,WHITE,M,GERMANTOWN,MD,MD,A - Marked Patrol,"(39.2017383333333, -77.2471966666667)"
493845,002ebdb6-a87a-42db-9fb1-90d595e5a86b,05/01/2014,22:28:00,MCP,"6th District, Gaithersburg / Montgomery Village",PASSENGER AGE 16 OR MORE IN REAR SEAT OF MOTOR...,270 SB AT SHADY GROVE RD,39.116255,-77.194197,No,...,22-412.3(c3),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.116255, -77.1941966666667)"
513741,002ebdb6-a87a-42db-9fb1-90d595e5a86b,05/01/2014,22:28:00,MCP,"6th District, Gaithersburg / Montgomery Village",PASSENGER AGE 16 OR MORE IN REAR SEAT OF MOTOR...,270 SB AT SHADY GROVE RD,39.116255,-77.194197,No,...,22-412.3(c3),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.116255, -77.1941966666667)"
538635,002ebdb6-a87a-42db-9fb1-90d595e5a86b,05/01/2014,22:28:00,MCP,"6th District, Gaithersburg / Montgomery Village",PASSENGER AGE 16 OR MORE IN REAR SEAT OF MOTOR...,270 SB AT SHADY GROVE RD,39.116255,-77.194197,No,...,22-412.3(c3),Transportation Article,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.116255, -77.1941966666667)"
1525469,0056143f-4023-43d6-8456-0c511a53c0f9,06/25/2018,22:35:00,MCP,"4th District, Wheaton",DRIVER FAILURE TO STOP AT STOP SIGN LINE,NOTLEY / NEW HAMPSHIRE AVE,39.077370,-77.000807,No,...,21-707(a),Transportation Article,False,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.07737, -77.0008066666667)"
1551882,0056143f-4023-43d6-8456-0c511a53c0f9,06/25/2018,22:35:00,MCP,"4th District, Wheaton",DRIVER FAILURE TO STOP AT STOP SIGN LINE,NOTLEY / NEW HAMPSHIRE AVE,39.077370,-77.000807,No,...,21-707(a),Transportation Article,False,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.07737, -77.0008066666667)"
1429328,0057cc49-c42d-4fdd-b5e4-72e6efbe2e04,01/28/2020,21:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER FAILING TO GIVE TURN SIGNAL CONTINUOUSL...,CLOPPER @ FIRSTFIELD,39.146432,-77.227727,No,...,21-604(d),Transportation Article,False,HISPANIC,M,GERMANTOWN,MD,DC,A - Marked Patrol,"(39.1464316666667, -77.2277266666667)"
1507826,0057cc49-c42d-4fdd-b5e4-72e6efbe2e04,01/28/2020,21:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER FAILING TO GIVE TURN SIGNAL CONTINUOUSL...,CLOPPER @ FIRSTFIELD,39.146432,-77.227727,No,...,21-604(d),Transportation Article,False,HISPANIC,M,GERMANTOWN,MD,DC,A - Marked Patrol,"(39.1464316666667, -77.2277266666667)"
247038,011d46db-1752-44cb-bdf6-c281b053725a,06/07/2015,13:58:00,MCP,"4th District, Wheaton",FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD S...,UNIVERSITY BLVD @ ELKIN ST,39.041667,-77.049510,No,...,22-412.2(d),Transportation Article,False,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0416666666667, -77.04951)"
257201,011d46db-1752-44cb-bdf6-c281b053725a,06/07/2015,13:58:00,MCP,"4th District, Wheaton",FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD S...,UNIVERSITY BLVD @ ELKIN ST,39.041667,-77.049510,No,...,22-412.2(d),Transportation Article,False,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0416666666667, -77.04951)"
390423,0129b005-5c48-442b-be86-811ca5407b14,02/23/2015,01:45:00,MCP,"5th District, Germantown",DRIVER ENTERING INTERSECTION AT FLASHING RED T...,NB RIDGE RD / OBSERVATION DR,39.224050,-77.261272,No,...,21-204(d),Transportation Article,False,WHITE,M,WASHINGTON,DC,DC,A - Marked Patrol,"(39.22405, -77.2612716666667)"
465992,0129b005-5c48-442b-be86-811ca5407b14,02/23/2015,01:45:00,MCP,"5th District, Germantown",DRIVER ENTERING INTERSECTION AT FLASHING RED T...,NB RIDGE RD / OBSERVATION DR,39.224050,-77.261272,No,...,21-204(d),Transportation Article,False,WHITE,M,WASHINGTON,DC,DC,A - Marked Patrol,"(39.22405, -77.2612716666667)"
676957,0156cf80-5d21-4767-b7e0-2038944167f4,07/13/2018,21:21:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD S...,701 RUSSELL AVE,39.153607,-77.207557,No,...,22-412.2(d),Transportation Article,False,HISPANIC,M,MONTGOMERY VILLAGE,MD,MD,A - Marked Patrol,"(39.1536066666667, -77.2075566666667)"
701976,0156cf80-5d21-4767-b7e0-2038944167f4,07/13/2018,21:21:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD S...,701 RUSSELL AVE,39.153607,-77.207557,No,...,22-412.2(d),Transportation Article,False,HISPANIC,M,MONTGOMERY VILLAGE,MD,MD,A - Marked Patrol,"(39.1536066666667, -77.2075566666667)"
716420,0156cf80-5d21-4767-b7e0-2038944167f4,07/13/2018,21:21:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILING TO SECURE CHILD UNDER AGE 8 IN CHILD S...,701 RUSSELL AVE,39.153607,-77.207557,No,...,22-412.2(d),Transportation Article,False,HISPANIC,M,MONTGOMERY VILLAGE,MD,MD,A - Marked Patrol,"(39.1536066666667, -77.2075566666667)"
1010482,015d99e8-9987-4adf-894d-bfe8c98c000b,05/24/2014,19:45:00,MCP,"3rd District, Silver Spring",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,PINEY BRANCH RD @ UNIVERSITY BLVD E,38.999707,-76.993443,No,...,13-401(h),Transportation Article,False,BLACK,M,GREENBELT,MD,MD,A - Marked Patrol,"(38.9997066666667, -76.9934433333333)"
1064893,015d99e8-9987-4adf-894d-bfe8c98c000b,05/24/2014,19:45:00,MCP,"3rd District, Silver Spring",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,PINEY BRANCH RD @ UNIVERSITY BLVD E,38.999707,-76.993443,No,...,13-401(h),Transportation Article,False,BLACK,M,GREENBELT,MD,MD,A - Marked Patrol,"(38.9997066666667, -76.9934433333333)"
1125778,017c2bf0-89c4-471f-a480-2b02f2fc3f1d,10/26/2014,09:53:00,MCP,"3rd District, Silver Spring",DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,FENTON AT ELLSWORTH,0.000000,0.000000,No,...,21-1124.2(d2),Transportation Article,False,BLACK,F,WILMINGTON,DE,DE,A - Marked Patrol,"(0.0, 0.0)"
1169403,017c2bf0-89c4-471f-a480-2b02f2fc3f1d,10/26/2014,09:53:00,MCP,"3rd District, Silver Spring",DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,FENTON AT ELLSWORTH,0.000000,0.000000,No,...,21-1124.2(d2),Transportation Article,False,BLACK,F,WILMINGTON,DE,DE,A - Marked Patrol,"(0.0, 0.0)"

In [10]:
# Dropping the duplicates
data = data.drop_duplicates()

In [11]:
data.duplicated().sum()

0

In [13]:
data.to_pickle("../checkpoints/checkpoint_removedDuplicates.pkl")

# Handling Other columns:

In [14]:
data.info()

<class 'pandas.DataFrame'>
Index: 2067761 entries, 0 to 2070114
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   SeqID                    str
 1   Date Of Stop             str
 2   Time Of Stop             str
 3   Agency                   str
 4   SubAgency                str
 5   Description              str
 6   Location                 str
 7   Latitude                 float64
 8   Longitude                float64
 9   Accident                 str
 10  Belts                    str
 11  Personal Injury          str
 12  Property Damage          str
 13  Fatal                    str
 14  Commercial License       str
 15  HAZMAT                   str
 16  Commercial Vehicle       str
 17  Alcohol                  str
 18  Work Zone                str
 19  Search Conducted         str
 20  Search Disposition       str
 21  Search Outcome           str
 22  Search Reason            str
 23  Search Reason For Stop   str
 24  Search Type              str
 25  Search Arrest Reason     str
 26  State                    str
 27  VehicleType              str
 28  Year                     float64
 29  Make                     str
 30  Model                    str
 31  Color                    str
 32  Violation Type           str
 33  Charge                   str
 34  Article                  str
 35  Contributed To Accident  bool
 36  Race                     str
 37  Gender                   str
 38  Driver City              str
 39  Driver State             str
 40  DL State                 str
 41  Arrest Type              str
 42  Geolocation              str
dtypes: bool(1), float64(3), str(39)
memory usage: 1.3 GB

### Date and Time of stop:

In [15]:
data['Date Of Stop'].shape

(2067761,)

In [16]:
data['Date Of Stop'].isnull().sum()

0

In [17]:
# Date of stop Format:05-01-2023
data['Date Of Stop'].astype(str).str.contains('-').sum()

0

In [18]:
data['Date Of Stop'].astype(str).str.contains('/').sum()

2067761

In [20]:
# Converting to DateTime:
data['Date Of Stop'] = pd.to_datetime(
    data['Date Of Stop'],
    errors = "coerce"# Will convert invalid data into NaT(Not a time)
).dt.date

In [21]:
data[data['Date Of Stop'].isna()]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation]
Index: []

[0 rows x 43 columns]

In [22]:
print("Max: ", max(data['Date Of Stop']))
print("Min: ", min(data['Date Of Stop']))

Max:  2025-12-05
Min:  2012-01-01

In [58]:
data.info()

<class 'pandas.DataFrame'>
Index: 2067761 entries, 0 to 2070114
Data columns (total 43 columns):
 #   Column                   Dtype
---  ------                   -----
 0   SeqID                    str
 1   Date Of Stop             datetime64[us]
 2   Time Of Stop             object
 3   Agency                   str
 4   SubAgency                str
 5   Description              str
 6   Location                 str
 7   Latitude                 float64
 8   Longitude                float64
 9   Accident                 str
 10  Belts                    str
 11  Personal Injury          str
 12  Property Damage          str
 13  Fatal                    str
 14  Commercial License       str
 15  HAZMAT                   str
 16  Commercial Vehicle       str
 17  Alcohol                  str
 18  Work Zone                str
 19  Search Conducted         str
 20  Search Disposition       str
 21  Search Outcome           str
 22  Search Reason            str
 23  Search Reason For Stop   str
 24  Search Type              str
 25  Search Arrest Reason     str
 26  State                    str
 27  VehicleType              str
 28  Year                     float64
 29  Make                     str
 30  Model                    str
 31  Color                    str
 32  Violation Type           str
 33  Charge                   str
 34  Article                  str
 35  Contributed To Accident  bool
 36  Race                     str
 37  Gender                   str
 38  Driver City              str
 39  Driver State             str
 40  DL State                 str
 41  Arrest Type              str
 42  Geolocation              str
dtypes: bool(1), datetime64[us](1), float64(3), object(1), str(37)
memory usage: 1.3+ GB

In [23]:
# Time Of Stop:
data[data['Time Of Stop'].astype(str).str.contains('.', regex=False)] # Checking if time of format(11.04.00)exists

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation]
Index: []

[0 rows x 43 columns]

In [24]:
data['Time Of Stop'] = pd.to_datetime(
    data['Time Of Stop'],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

In [25]:
data[data['Time Of Stop'].isna()]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation]
Index: []

[0 rows x 43 columns]

In [26]:
data.columns

Index(['SeqID', 'Date Of Stop', 'Time Of Stop', 'Agency', 'SubAgency',
       'Description', 'Location', 'Latitude', 'Longitude', 'Accident', 'Belts',
       'Personal Injury', 'Property Damage', 'Fatal', 'Commercial License',
       'HAZMAT', 'Commercial Vehicle', 'Alcohol', 'Work Zone',
       'Search Conducted', 'Search Disposition', 'Search Outcome',
       'Search Reason', 'Search Reason For Stop', 'Search Type',
       'Search Arrest Reason', 'State', 'VehicleType', 'Year', 'Make', 'Model',
       'Color', 'Violation Type', 'Charge', 'Article',
       'Contributed To Accident', 'Race', 'Gender', 'Driver City',
       'Driver State', 'DL State', 'Arrest Type', 'Geolocation'],
      dtype='str')

In [27]:
data['Stop_dateTime'] = pd.to_datetime(
    data['Date Of Stop'].astype(str)+" "
    + data['Time Of Stop'].astype(str),
    errors = "coerce"
)

In [28]:
data['Stop_dateTime'].head(5)

0   2023-05-01 23:11:00
1   2023-08-31 16:41:00
2   2023-08-31 16:41:00
3   2023-08-31 16:41:00
4   2023-08-31 16:41:00
Name: Stop_dateTime, dtype: datetime64[us]

In [29]:
data['Accident'].value_counts(dropna = False)

Accident
No     2011283
Yes      56478
Name: count, dtype: int64

In [31]:
data.to_pickle("../checkpoints/checkpoint_dateTime.pkl")

## Boolean Columns:

In [32]:
# Boolean Columns:

boolean_columns = ['Accident', 'Belts',
       'Personal Injury', 'Property Damage', 'Fatal', 'Commercial License',
       'HAZMAT', 'Commercial Vehicle', 'Alcohol']

for i in boolean_columns:
    print(data[i].value_counts(dropna = False))

Accident
No     2011283
Yes      56478
Name: count, dtype: int64
Belts
No     2003455
Yes      64306
Name: count, dtype: int64
Personal Injury
No     2042652
Yes      25109
Name: count, dtype: int64
Property Damage
No     2022620
Yes      45141
Name: count, dtype: int64
Fatal
No     2067194
Yes        567
Name: count, dtype: int64
Commercial License
No     2009984
Yes      57777
Name: count, dtype: int64
HAZMAT
No     2067608
Yes        153
Name: count, dtype: int64
Commercial Vehicle
No     2061155
Yes       6606
Name: count, dtype: int64
Alcohol
No     2065146
Yes       2615
Name: count, dtype: int64

In [33]:
for i in boolean_columns:
    print("\n",i)
    print(data[i].isna().sum())

 Accident
0

 Belts
0

 Personal Injury
0

 Property Damage
0

 Fatal
0

 Commercial License
0

 HAZMAT
0

 Commercial Vehicle
0

 Alcohol
0

In [34]:
for i in boolean_columns:
    data[i] = data[i].map({
        'No':False,
        'Yes':True
    })

In [35]:
for i in boolean_columns:
    print(data[i].value_counts())

Accident
False    2011283
True       56478
Name: count, dtype: int64
Belts
False    2003455
True       64306
Name: count, dtype: int64
Personal Injury
False    2042652
True       25109
Name: count, dtype: int64
Property Damage
False    2022620
True       45141
Name: count, dtype: int64
Fatal
False    2067194
True         567
Name: count, dtype: int64
Commercial License
False    2009984
True       57777
Name: count, dtype: int64
HAZMAT
False    2067608
True         153
Name: count, dtype: int64
Commercial Vehicle
False    2061155
True        6606
Name: count, dtype: int64
Alcohol
False    2065146
True        2615
Name: count, dtype: int64

In [36]:
data.to_pickle("../checkpoints/checkpoint_boolcols.pkl")

## Agency and SubAgency:

In [37]:
# Agency:
print(data['Agency'].value_counts(dropna=False))
print(data['Agency'].shape)
print(data['Agency'].isnull().sum())

Agency
MCP    2067761
Name: count, dtype: int64
(2067761,)
0

In [38]:
# SubAgency
print(data['SubAgency'].value_counts(dropna=False))
print(data['SubAgency'].shape)
print(data['SubAgency'].isnull().sum())

SubAgency
4th District, Wheaton                              448580
3rd District, Silver Spring                        373052
2nd District, Bethesda                             325179
6th District, Gaithersburg / Montgomery Village    261210
5th District, Germantown                           245529
1st District, Rockville                            240652
Headquarters and Special Operations                173549
W15                                                     7
S15                                                     3
Name: count, dtype: int64
(2067761,)
0

In [39]:
data[data['SubAgency'].isin(['W15','S15'])].head(5)

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Article,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation,Stop_dateTime
943162,a6bef0fc-2792-4c6c-b88e-c80325dc2421,2013-02-03,07:05:00,MCP,W15,DRIVING A MOTOR VEHICLE WITHOUT LIGHTED HEAD L...,RANDOLPH/HAMTON RD,39.069158,-77.014373,False,...,Transportation Article,False,BLACK,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0691583333333, -77.0143733333333)",2013-02-03 07:05:00
944601,44d25d05-13f3-4b96-b8d7-846eae4b3842,2013-01-29,21:08:00,MCP,S15,DRIVING VEHICLE ON HIGHWAY WITHOUT CURRENT REG...,CHERRY HILL RD AT FDA BLVD,39.044690,-76.951778,False,...,Transportation Article,False,WHITE,M,ANNAPOLIS,MD,MD,A - Marked Patrol,"(39.0446903333333, -76.9517781666667)",2013-01-29 21:08:00
1415136,44d25d05-13f3-4b96-b8d7-846eae4b3842,2013-01-29,21:08:00,MCP,S15,DISPLAYING EXPIRED REGISTRATION PLATE ISSUED B...,CHERRY HILL RD AT FDA BLVD,39.044690,-76.951778,False,...,Transportation Article,False,WHITE,M,ANNAPOLIS,MD,MD,A - Marked Patrol,"(39.0446903333333, -76.9517781666667)",2013-01-29 21:08:00
1439590,2acc0d97-2107-4a9a-8c9f-c237e67205a0,2013-04-18,05:27:00,MCP,W15,RT. TURN FROM IMPROPER ROAD POSITION,VEIRS MILL RD @ TWINBROOK PARKWAY,39.075793,-77.111380,False,...,Transportation Article,False,ASIAN,M,ROCKVILLE,MD,MD,A - Marked Patrol,"(39.0757933333333, -77.11138)",2013-04-18 05:27:00
1439752,2acc0d97-2107-4a9a-8c9f-c237e67205a0,2013-04-18,05:27:00,MCP,W15,DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC...,VEIRS MILL RD @ TWINBROOK PARKWAY,39.075793,-77.111380,False,...,Transportation Article,False,ASIAN,M,ROCKVILLE,MD,MD,A - Marked Patrol,"(39.0757933333333, -77.11138)",2013-04-18 05:27:00

In [40]:
data['SubAgency'] = data['SubAgency'].astype(str).str.strip()

In [41]:
data.to_pickle("../checkpoints/checkpoint_Agencies.pkl")

## WorkZone

In [42]:
# WorkZone:

data['Work Zone'] = data['Work Zone'].map({
    'No': False,
    'Yes':True
})

In [43]:
print(data[data['Work Zone']==True].head(3))

                                      SeqID Date Of Stop Time Of Stop Agency  \
322    a71de7b0-9067-4f66-af45-461366346463   2023-09-01     09:38:00    MCP
2762   1eb8c751-88f2-477f-9d71-1f43c2284529   2023-05-04     23:29:00    MCP
27867  c2cf94f2-72f2-40b2-ae5d-65b59e0dccc8   2023-06-15     21:04:00    MCP

                                             SubAgency  \
322                Headquarters and Special Operations
2762   6th District, Gaithersburg / Montgomery Village
27867                          1st District, Rockville

                                             Description             Location  \
322    DRIVER WRITING,SENDING,READING A TEXT,ELECTRON...   4101 ASPIN HILL RD
2762   DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...  31 SOUTH SUMMIT AVE
27867  DRIVING VEHICLE IN EXCESS OF REASONABLE AND PR...  1800 E JEFFESRON ST

        Latitude  Longitude  Accident  ...                 Article  \
322     0.000000     0.0000     False  ...  Transportation Article
2762    0.000000     0.0000     False  ...  Transportation Article
27867  39.113796   -77.2356     False  ...  Transportation Article

       Contributed To Accident      Race  Gender   Driver City  Driver State  \
322                      False  HISPANIC       M     ROCKVILLE            MD
2762                     False  HISPANIC       M  GAITHERSBURG            MD
27867                    False     BLACK       M    WASHINGTON            DC

       DL State        Arrest Type                            Geolocation  \
322          MD  A - Marked Patrol                             (0.0, 0.0)
2762         MD  A - Marked Patrol                             (0.0, 0.0)
27867        XX  A - Marked Patrol  (39.1137963333333, -77.2356001666667)

            Stop_dateTime
322   2023-09-01 09:38:00
2762  2023-05-04 23:29:00
27867 2023-06-15 21:04:00

[3 rows x 44 columns]

In [ ]:
Date Of Stop = datetime
Time Of Stop = HH:MM:SS
Latitude  = Numeric
Longitude = Numeric
Year = Numeric

## Location, Latitude, Longitude

In [44]:
data['Location'].value_counts(dropna=False)

Location
MONTGOMERY VILLAGE AVE @ RUSSELL AVE    2449
WAYNE AVE @ DALE DR                     2331
WOODFIELD RD @ EMORY GROVE RD           2202
IS 370 @ IS 270                         1982
RT 28 @ BLACKBERRY DR                   1966
                                        ...
WATKINS MILL HS                            1
CONNECTICUT AVE @ JEFFY ST                 1
MORNINGWOOD DR/SUNSET RIVER CT             1
WATKINS MILL RD /SPECTRUM DR               1
MASS AVE @ SANGAMORE                       1
Name: count, Length: 269353, dtype: int64

In [95]:
data['Location_clean'] = data['Location'].str.replace("@","/", regex = False)

In [106]:
data['Location_clean'].astype(str).str.contains('/').sum()

1857047

In [102]:
data['Location'].shape

(2067761,)

In [103]:
data['Location_clean'].astype(str).str.contains('@', regex=False).sum()

0

In [107]:
data[
    ~data['Location_clean']
    .astype(str)
    .str.contains('/', regex=False)
]['Location_clean'].sample(20)

587471                           350 E GUDE DRIVE
1848153                      12276 ROCKVILLE PIKE
699270                         26400 WOODFIELD RD
107477                             11900 RIVER RD
606576              KENT ST ON KENSINGTON PKWY SB
214772                        11231 VEIRS MILL RD
1789268                     13281 LAKE GENEVA WAY
152000                 22520 GATEWAY CENTER DRIVE
1499611                          8040 13TH STREET
1164274    CONNECTICUT AVE ENTRANCE TO HOME DEPOT
1148021                       2300 BLK BEL PRE RD
1469371                           149 ROLLINS AVE
278328                           1911 SEMINARY RD
1443732        OLD GEORGETOWN RD X EXECUTIVE BLVD
578581                     13800 BLK OUTLET DRIVE
467000                          14201 GEORGIA AVE
1097022                    I370 ENTRANCE TO METRO
65293            2800 BLK OF UNIVERSITY BLVD WEST
2053686      300 N FREDERICK  AVE,GAITHERSBURG,MD
1955635                     650 UNIVERSITY BLVD E
Name: Location_clean, dtype: str

In [45]:
data['Location_clean'] = (
    data['Location']
    .str.upper()
    .str.replace('@', '/', regex=False)
    .str.replace(' AND ', ' / ', regex=False)
    .str.replace(' AT ', ' / ', regex=False)
    .str.replace(' & ', ' / ', regex=False)
)

In [46]:
print(data['Location'].isnull().sum())
print(data['Location_clean'].isnull().sum())

4
4

In [47]:
data[data['Accident']==False]

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation,Stop_dateTime,Location_clean
0,52282e8c-f2e1-4bb5-8509-2d5e4f8da8ca,2023-05-01,23:11:00,MCP,"3rd District, Silver Spring",OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,BRIGGS CHANEY RD @ COLUMIBA PIKE,0.000000,0.000000,False,...,False,WHITE,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(0.0, 0.0)",2023-05-01 23:11:00,BRIGGS CHANEY RD / COLUMIBA PIKE
1,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
2,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
3,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
4,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070110,242e2d07-6bf2-4648-8c22-8b06f37ce91f,2025-12-04,13:14:00,MCP,"2nd District, Bethesda",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,RAMSEY AVE/WAYNE AVE,38.993932,-77.027828,False,...,False,BLACK,M,LAUREL,MD,MD,A - Marked Patrol,"(38.9939315, -77.0278283333333)",2025-12-04 13:14:00,RAMSEY AVE/WAYNE AVE
2070111,0cb33bba-d1bc-424e-8c28-6943627c5845,2025-12-04,15:14:00,MCP,"4th District, Wheaton",PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUB...,GEORGIA AVE/ARCOLA AVE,0.000000,0.000000,False,...,False,BLACK,M,STATEN ISLAND,NY,NY,A - Marked Patrol,"(0.0, 0.0)",2025-12-04 15:14:00,GEORGIA AVE/ARCOLA AVE
2070112,cb00a667-2837-4e57-8cff-103106fca828,2025-12-04,21:18:00,MCP,"3rd District, Silver Spring",DRIVER CHANGING LANES WHEN UNSAFE,E RANDOLPH ROAD/OLD COLUMBIA PIKE,0.000000,0.000000,False,...,False,BLACK,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(0.0, 0.0)",2025-12-04 21:18:00,E RANDOLPH ROAD/OLD COLUMBIA PIKE
2070113,3c842be5-9cd1-43a0-85bd-28c835aca357,2025-12-04,07:28:00,MCP,"1st District, Rockville",EXCEEDING THE POSTED SPEED LIMIT OF 25 MPH,GAINSBOROUGH RD @ HOB NAIL CT,39.034735,-77.174082,False,...,False,WHITE,F,POTOMAC,MD,MD,R - Unmarked Laser,"(39.034735, -77.1740816666667)",2025-12-04 07:28:00,GAINSBOROUGH RD / HOB NAIL CT
2070114,047a24ba-9537-48ab-b4ce-c17386715d0f,2025-12-04,13:33:00,MCP,"5th District, Germantown",DISPLAYING EXPIRED REGISTRATION PLATE ISSUED B...,WOODFIELD DR @ FLOWER HILL WAY,39.156796,-77.163849,False,...,False,HISPANIC,M,PACOIMA,CA,CA,B - Unmarked Patrol,"(39.1567958333333, -77.1638485)",2025-12-04 13:33:00,WOODFIELD DR / FLOWER HILL WAY

In [48]:
data[data['Location_clean'].isnull()]

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation,Stop_dateTime,Location_clean
614118,98a34f6c-ad4e-4cdd-bf09-bcc1ad19cf73,2013-08-30,23:39:00,MCP,Headquarters and Special Operations,DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,NaN,39.006675,-77.075320,False,...,False,WHITE,M,BETHESDA,MD,MD,O - Foot Patrol,"(39.006675, -77.07532)",2013-08-30 23:39:00,NaN
1717948,d7f6f8be-d6d6-4284-af8a-46e7e316325a,2023-01-01,21:57:00,MCP,"5th District, Germantown",DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC...,NaN,39.199285,-77.255743,False,...,False,OTHER,F,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.199285, -77.2557435)",2023-01-01 21:57:00,NaN
1748016,d7f6f8be-d6d6-4284-af8a-46e7e316325a,2023-01-01,21:57:00,MCP,"5th District, Germantown",FAILURE OF INDIVIDUAL DRIVING ON HIGHWAY TO DI...,NaN,39.199285,-77.255743,False,...,False,OTHER,F,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.199285, -77.2557435)",2023-01-01 21:57:00,NaN
1824401,98a34f6c-ad4e-4cdd-bf09-bcc1ad19cf73,2013-08-30,23:39:00,MCP,Headquarters and Special Operations,Glass (*),NaN,39.006675,-77.075320,False,...,False,WHITE,M,BETHESDA,MD,MD,O - Foot Patrol,"(39.006675, -77.07532)",2013-08-30 23:39:00,NaN

In [49]:
# Latitude and Longitude:
data['Latitude'] = pd.to_numeric(
    data['Latitude'],
    errors = "coerce"
)

data['Longitude'] = pd.to_numeric(
    data['Longitude'],
    errors = "coerce"
)

In [50]:
data['Latitude'] = data['Latitude'].replace(0,np.nan)
data['Longitude'] = data['Longitude'].replace(0,np.nan)

In [51]:
(data['Latitude']==0).sum()

0

In [52]:
# Validating Range:
data['Latitude'].describe()
print(data['Longitude'].describe())

count    1.912017e+06
mean    -7.711641e+01
std      2.361188e-01
min     -1.512560e+02
25%     -7.720103e+01
50%     -7.709804e+01
75%     -7.704663e+01
max      3.906444e+01
Name: Longitude, dtype: float64

In [53]:
data[
    (data["Latitude"] < -90) |
    (data["Latitude"] > 90)
]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation, Stop_dateTime, Location_clean]
Index: []

[0 rows x 45 columns]

In [121]:
data[
    (data["Longitude"] < -180) |
    (data["Longitude"] > 180)
]

Empty DataFrame
Columns: [SeqID, Date Of Stop, Time Of Stop, Agency, SubAgency, Description, Location, Latitude, Longitude, Accident, Belts, Personal Injury, Property Damage, Fatal, Commercial License, HAZMAT, Commercial Vehicle, Alcohol, Work Zone, Search Conducted, Search Disposition, Search Outcome, Search Reason, Search Reason For Stop, Search Type, Search Arrest Reason, State, VehicleType, Year, Make, Model, Color, Violation Type, Charge, Article, Contributed To Accident, Race, Gender, Driver City, Driver State, DL State, Arrest Type, Geolocation, Stop_dateTime, Location_clean]
Index: []

[0 rows x 45 columns]

In [54]:
data[
    (data["Longitude"] >= -125) &
    (data["Longitude"] <= -65)
]

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Contributed To Accident,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation,Stop_dateTime,Location_clean
1,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVING TO DRIVE MOTOR VEHICLE ON HIGHWAY WITH...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
2,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
3,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOS...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
4,b66f253b-af29-4bc4-bb73-93755ca2a779,2023-08-31,16:41:00,MCP,"6th District, Gaithersburg / Montgomery Village",FAILURE TO CONTROL VEH. SPEED ON HWY. TO AVOID...,OAKMONT AVE @ GROVEMONT CIR,39.097965,-77.153010,False,...,False,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.097965, -77.15301)",2023-08-31 16:41:00,OAKMONT AVE / GROVEMONT CIR
5,971ef50f-f138-419f-89e5-5d2cc5d7b75a,2023-04-30,23:55:00,MCP,"4th District, Wheaton",DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGI...,KEMP MILL ROAD @ ALPERT LANE,39.053038,-77.024637,False,...,False,WHITE,F,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0530383333333, -77.0246366666667)",2023-04-30 23:55:00,KEMP MILL ROAD / ALPERT LANE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2070108,e96ad85f-0df4-4116-9321-c7ae43b81365,2025-12-04,10:41:00,MCP,"2nd District, Bethesda",UNAUTHORIZED DISPLAY AND USE OF REGISTRATION P...,EAST WEST HIGHWAY/COLESVILLE RD,38.994304,-77.031229,False,...,False,BLACK,F,CLINTON,MD,MD,A - Marked Patrol,"(38.9943045, -77.0312291666667)",2025-12-04 10:41:00,EAST WEST HIGHWAY/COLESVILLE RD
2070109,d9edb02e-724c-4cd6-83b1-c6f842640587,2025-12-05,06:43:00,MCP,"5th District, Germantown",PARKING WHERE PROHIBITED BY OFFICIAL SIGNS,PICKERING PL @ THUNDERHEAD DR,39.188985,-77.271245,False,...,False,HISPANIC,M,GELN BURNIE,MD,MD,A - Marked Patrol,"(39.188985, -77.271245)",2025-12-05 06:43:00,PICKERING PL / THUNDERHEAD DR
2070110,242e2d07-6bf2-4648-8c22-8b06f37ce91f,2025-12-04,13:14:00,MCP,"2nd District, Bethesda",FAILURE TO DISPLAY REGISTRATION CARD UPON DEMA...,RAMSEY AVE/WAYNE AVE,38.993932,-77.027828,False,...,False,BLACK,M,LAUREL,MD,MD,A - Marked Patrol,"(38.9939315, -77.0278283333333)",2025-12-04 13:14:00,RAMSEY AVE/WAYNE AVE
2070113,3c842be5-9cd1-43a0-85bd-28c835aca357,2025-12-04,07:28:00,MCP,"1st District, Rockville",EXCEEDING THE POSTED SPEED LIMIT OF 25 MPH,GAINSBOROUGH RD @ HOB NAIL CT,39.034735,-77.174082,False,...,False,WHITE,F,POTOMAC,MD,MD,R - Unmarked Laser,"(39.034735, -77.1740816666667)",2025-12-04 07:28:00,GAINSBOROUGH RD / HOB NAIL CT
2070114,047a24ba-9537-48ab-b4ce-c17386715d0f,2025-12-04,13:33:00,MCP,"5th District, Germantown",DISPLAYING EXPIRED REGISTRATION PLATE ISSUED B...,WOODFIELD DR @ FLOWER HILL WAY,39.156796,-77.163849,False,...,False,HISPANIC,M,PACOIMA,CA,CA,B - Unmarked Patrol,"(39.1567958333333, -77.1638485)",2025-12-04 13:33:00,WOODFIELD DR / FLOWER HILL WAY

In [55]:
data = data[
    (data["Longitude"] >= -125) &
    (data["Longitude"] <= -65)
]

In [56]:
data.shape

(1912007, 45)

## Description:

In [179]:
data['Description'] = data['Description'].astype(str).str.strip().str.upper()

In [180]:
data["Description"].value_counts().head(20)

Description
DRIVER FAILURE TO OBEY PROPERLY PLACED TRAFFIC CONTROL DEVICE INSTRUCTIONS                              159797
FAILURE TO DISPLAY REGISTRATION CARD UPON DEMAND BY POLICE OFFICER                                       84600
DRIVING VEHICLE ON HIGHWAY WITH SUSPENDED REGISTRATION                                                   56279
DISPLAYING EXPIRED REGISTRATION PLATE ISSUED BY ANY STATE                                                53762
FAILURE OF INDIVIDUAL DRIVING ON HIGHWAY TO DISPLAY LICENSE TO UNIFORMED POLICE ON DEMAND                51494
DRIVER USING HANDS TO USE HANDHELD TELEPHONE WHILEMOTOR VEHICLE IS IN MOTION                             46794
EXCEEDING THE POSTED SPEED LIMIT OF 40 MPH                                                               42217
DRIVER FAILURE TO STOP AT STOP SIGN LINE                                                                 41497
EXCEEDING THE POSTED SPEED LIMIT OF 35 MPH                                                               39366
DRIVING VEHICLE ON HIGHWAY WITHOUT CURRENT REGISTRATION PLATES AND VALIDATION TABS                       35269
PERSON DRIVING MOTOR VEHICLE ON HIGHWAY OR PUBLIC USE PROPERTY ON SUSPENDED LICENSE AND PRIVILEGE        33988
EXCEEDING THE POSTED SPEED LIMIT OF 30 MPH                                                               32125
STOP LIGHTS (*)                                                                                          29714
NEGLIGENT DRIVING VEHICLE IN CARELESS AND IMPRUDENT MANNER ENDANGERING PROPERTY, LIFE AND PERSON         26455
DRIVER CHANGING LANES WHEN UNSAFE                                                                        25410
FAILURE OF VEH. ON HWY. TO DISPLAY LIGHTED LAMPS, ILLUMINATING DEVICE IN UNFAVORABLE VISIBILITY COND     24924
DRIVING MOTOR VEHICLE ON HIGHWAY WITHOUT REQUIRED LICENSE AND AUTHORIZATION                              24864
DRIVER FAILURE TO STOP AT STEADY CIRCULAR RED SIGNAL                                                     22233
FAILURE TO ATTACH VEHICLE REGISTRATION PLATES AT FRONT AND REAR                                          21373
OPERATING VEHICLE ON HIGHWAY WITH UNAUTHORIZED WINDOW TINTING MATERIAL                                   20428
Name: count, dtype: int64

In [171]:
def categorize_violation(desc):

    if pd.isna(desc):
        return "UNKNOWN"

    desc = str(desc).upper()

    if "SPEED" in desc:
        return "SPEEDING"

    elif "REG." in desc or "REGISTRATION" in desc or "PLATE" in desc:
        return "REGISTRATION"

    elif "LIC." in desc or "LICENSE" in desc or "PERMIT" in desc:
        return "LICENSE"

    elif "STOP SIGN" in desc or "RED SIGNAL" in desc:
        return "TRAFFIC_CONTROL"

    elif "TELEPHONE" in desc:
        return "DISTRACTED_DRIVING"
    
    elif "TRAFFIC CONTROL DEVICE" in desc:
        return "TRAFFIC_CONTROL"

    elif "NEGLIGENT" in desc or "RECKLESS" in desc:
        return "RECKLESS_DRIVING"

    elif "LANE" in desc:
        return "LANE_VIOLATION"

    elif "STOP LIGHT" in desc or "RED TRAFFIC SIGNAL" in desc:
        return "TRAFFIC_SIGNAL"

    elif "LIGHT" in desc or "LAMP" in desc or "HEADLIGHT" in desc or "TAILLIGHT" in desc:
        return "VEHICLE_LIGHTING"

    elif "WINDOW TINT" in desc or "TINT" in desc:
        return "WINDOW_TINT"

    elif "ALCOHOL" in desc:
        return "DUI"

    elif "SEATBELT" in desc or "SEAT BELT" in desc:
        return "SEAT_BELT"

    elif "EQUIPMENT" in desc:
        return "VEHICLE_EQUIPMENT"

    elif "UNINSURED" in desc:
        return "INSURANCE"

    elif "PEDESTRIAN" in desc:
        return "PEDESTRIAN"

    elif "CHILD SAFETY SEAT" in desc:
        return "CHILD_SAFETY"

    elif "PARKING" in desc:
        return "PARKING"
    elif "YIELD" in desc:
        return "RIGHT_OF_WAY"
    elif "FOLLOWING" in desc:
        return "FOLLOWING_DISTANCE"
    elif "TURN" in desc:
        return "TURNING_VIOLATION"
    elif "ACCIDENT" in desc or "SCENE" in desc:
        return "ACCIDENT_RELATED"
    elif "TEXT" in desc or "EARPHONE" in desc:
        return "DISTRACTED_DRIVING"
    elif "SECURITY" in desc or "INSURANCE" in desc:
        return "INSURANCE"
    else:
        return "OTHER"

In [181]:
data['Violation_category'] = data['Description'].apply(categorize_violation)

In [182]:
data['Violation_category'].value_counts()

Violation_category
SPEEDING              338378
REGISTRATION          329486
TRAFFIC_CONTROL       256856
LICENSE               241577
VEHICLE_LIGHTING      135605
OTHER                 131209
TRAFFIC_SIGNAL         73379
DUI                    57664
DISTRACTED_DRIVING     53352
LANE_VIOLATION         52732
RECKLESS_DRIVING       39404
WINDOW_TINT            34476
SEAT_BELT              32451
INSURANCE              20461
RIGHT_OF_WAY           20181
TURNING_VIOLATION      18586
VEHICLE_EQUIPMENT      17672
PARKING                13836
ACCIDENT_RELATED       10094
FOLLOWING_DISTANCE      8846
PEDESTRIAN              8044
CHILD_SAFETY            5007
UNKNOWN                    8
Name: count, dtype: int64

## Search Columns:

In [63]:
# Search Conducted
data['Search Conducted'].value_counts(dropna=False)

Search Conducted
No     1107552
NaN     727621
Yes      76834
Name: count, dtype: int64

In [64]:
search_columns=['Search Conducted', 'Search Disposition', 'Search Outcome',
       'Search Reason', 'Search Reason For Stop', 'Search Type',
       'Search Arrest Reason']

In [65]:
data.loc[data['Search Conducted'].isna(), search_columns].isnull().sum()

Search Conducted          727621
Search Disposition        727621
Search Outcome            727621
Search Reason             727621
Search Reason For Stop    727621
Search Type               727621
Search Arrest Reason      727621
dtype: int64

In [66]:
# Here, all the other search columns are also Nan..This means that no search was conducted, it is not just missing data
data['Search Conducted'] = data['Search Conducted'].fillna('No')

In [67]:
data['Search Conducted'].value_counts()

Search Conducted
No     1835173
Yes      76834
Name: count, dtype: int64

In [68]:
data['Search Disposition'].value_counts(dropna = False)

Search Disposition
NaN                        1835173
Nothing                      32865
Contraband Only              20462
Property Only                12667
Contraband and Property      10825
DUI                             12
nothing                          3
Name: count, dtype: int64

In [69]:
data['Search Disposition'] = data['Search Disposition'].fillna("Not Applicable")

In [70]:
data['Search Disposition'].value_counts(dropna = False)

Search Disposition
Not Applicable             1835173
Nothing                      32865
Contraband Only              20462
Property Only                12667
Contraband and Property      10825
DUI                             12
nothing                          3
Name: count, dtype: int64

In [71]:
data['Search Disposition'] = data['Search Disposition'].str.strip().str.title()

In [72]:
#Search Outcome
data['Search Outcome'].value_counts(dropna=False)

Search Outcome
NaN                   745615
Warning               598595
Citation              480855
Arrest                 52708
SERO                   34231
Recovered Evidence         3
Name: count, dtype: int64

In [73]:
data['Search Outcome'] =data['Search Outcome'].str.replace("Na","NA")

In [74]:
data['Search Outcome'] = data['Search Outcome'].str.strip().str.title()

In [75]:
# Search Reason
data['Search Reason'].value_counts(dropna = False)

Search Reason
NaN                       1835173
Incident to Arrest          42500
Probable Cause              19875
Consensual                  11304
K-9                          1732
Other                         950
Exigent Circumstances         461
Probable Cause for CDS          5
Arrest/Tow                      3
plain view marijuana            3
DUI                             1
Name: count, dtype: int64

In [76]:
data['Search Reason'] = data['Search Reason'].str.strip().str.title()

In [77]:
data['Search Reason'] = data['Search Reason'].fillna("NA")

In [78]:
#Search Reason For Stop
data['Search Reason For Stop'].value_counts(dropna = False)

Search Reason For Stop
NaN              727818
21-201(a1)       144001
21-801.1          90488
13-411(f)         63260
21-707(a)         55552
                  ...
16-101(a2)            1
11-395.3A(1)          1
21-1205.1(b2)         1
22-222(a2)            1
21-510(a)             1
Name: count, Length: 819, dtype: int64

In [79]:
data['Search Reason For Stop'] = data['Search Reason For Stop'].fillna("NA")

In [80]:
# Search Type
data['Search Type'].value_counts(dropna = False)

Search Type
NaN                  1835180
Both                   57735
Property               10498
Person                  8584
car                        4
Search Incidental          3
PC                         3
Name: count, dtype: int64

In [81]:
data['Search Type'] = data['Search Type'].fillna("Not Applicable")

In [85]:
#  Search Arrest Reason
data['Search Arrest Reason'].value_counts(dropna = False)

Search Arrest Reason
Not Applicable    1859968
Stop                33155
Search              10532
Other                5425
Warrant              2873
Traffic                24
Dui                    13
Alcohol                 6
Marihuana               5
Criminal                3
Driving                 3
Name: count, dtype: int64

In [83]:
data['Search Arrest Reason'] = data['Search Arrest Reason'].str.strip().str.title()

In [84]:
data['Search Arrest Reason'] = data['Search Arrest Reason'].fillna("Not Applicable")

## State, VehicleType and Year:

In [86]:
data['State'].value_counts(dropna = False)

State
MD    1661299
VA      90237
DC      47104
XX      15178
PA      13166
       ...
NF          2
MH          2
NU          1
AS          1
IT          1
Name: count, Length: 73, dtype: int64

In [87]:
data['State'] = data['State'].str.strip().str.upper()

In [88]:
data[data['State'] == 'XX'].sample(20)

,SeqID,Date Of Stop,Time Of Stop,Agency,SubAgency,Description,Location,Latitude,Longitude,Accident,...,Race,Gender,Driver City,Driver State,DL State,Arrest Type,Geolocation,Stop_dateTime,Location_clean,Violation_category
689562,c9902b55-4f19-44f3-b935-408561c670ab,2018-07-03,22:06:00,MCP,"3rd District, Silver Spring",PEDESTRIAN WALKING ALONG AND ON ADJACENT ROADW...,11431 LOCKWOOD DRIVE,39.041167,-76.987245,False,...,BLACK,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0411666666667, -76.987245)",2018-07-03 22:06:00,11431 LOCKWOOD DRIVE,OTHER
1131590,62967fb5-6b7a-4d69-a20a-e48f5fb0087c,2019-06-14,16:23:00,MCP,"5th District, Germantown",DRIVER FAILURE TO STOP FOR PEDESTRIAN IN CROSS...,RIDGE AND HIGH CORNER,39.299483,-77.200480,False,...,BLACK,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.2994833333333, -77.20048)",2019-06-14 16:23:00,RIDGE / HIGH CORNER,OTHER
777001,b93c0b5f-ab6a-44a4-8fcf-f7c2cf7215b7,2015-05-27,09:54:00,MCP,"6th District, Gaithersburg / Montgomery Village",KNOWINGLY HOLDING FALSIFIED VEH. REG. PLATE,KENTLANDS BLVD @ BEACON SQUARE,39.125408,-77.242127,False,...,WHITE,M,DERWOOD,MD,MD,A - Marked Patrol,"(39.1254083333333, -77.2421266666667)",2015-05-27 09:54:00,KENTLANDS BLVD / BEACON SQUARE,OTHER
129278,1be82228-5e3d-4468-9378-4a4bed3e9271,2013-06-21,21:45:00,MCP,"6th District, Gaithersburg / Montgomery Village",OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY,10313 WATKINS MILL DR,39.168323,-77.212331,False,...,HISPANIC,M,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.16832335, -77.2123312833333)",2013-06-21 21:45:00,10313 WATKINS MILL DR,OTHER
496436,500c357c-309a-4701-a7dc-8e3d947c6fd1,2015-04-01,12:15:00,MCP,"6th District, Gaithersburg / Montgomery Village",PEDESTRIAN CROSSING ROADWAY BETWEEN ADJACENT I...,ODENDHAL AVE/ RUSSELL AVE,39.151542,-77.202065,False,...,HISPANIC,F,GAITHERSBURG,MD,MD,A - Marked Patrol,"(39.1515416666667, -77.202065)",2015-04-01 12:15:00,ODENDHAL AVE/ RUSSELL AVE,OTHER
1228923,aabb979e-1ef0-4f12-91dc-559d6deae9ed,2019-06-23,11:34:00,MCP,"5th District, Germantown","DRIVER FAIL TO MAKE REQUIRED STOP AT SIGN, PAV...",BARNSVILLE RD & OLD HUNDRED RD,39.220844,-77.375516,False,...,WHITE,M,WASHINGTON,DC,DC,A - Marked Patrol,"(39.2208441666667, -77.3755156666667)",2019-06-23 11:34:00,BARNSVILLE RD / OLD HUNDRED RD,OTHER
1782739,e6e5d441-2a1c-4c5f-81de-5523bfb3fd40,2022-04-21,12:21:00,MCP,"6th District, Gaithersburg / Montgomery Village","PEDESTRIAN FAIL TO OBEY ""UPRAISED HAND"" SIGNAL",N FREDERICK AVE / TRAVIS AVE,39.162072,-77.221825,False,...,BLACK,M,GERMANTOWN,MD,MD,A - Marked Patrol,"(39.1620716666667, -77.221825)",2022-04-21 12:21:00,N FREDERICK AVE / TRAVIS AVE,OTHER
508833,e85aab1f-360d-453e-86d0-6ef7b091a18b,2016-03-31,22:36:00,MCP,"4th District, Wheaton",FAILURE TO DRIVE VEHICLE ON RIGHT HALF OF ROAD...,NEW HAMPSHIRE AVE / HARDING LANE,39.057935,-77.048563,True,...,WHITE,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.057935, -77.0485633333333)",2016-03-31 22:36:00,NEW HAMPSHIRE AVE / HARDING LANE,OTHER
1986296,16b9169f-c37e-46f1-acda-78c5e389bf11,2024-11-26,10:47:00,MCP,"6th District, Gaithersburg / Montgomery Village",DRIVER USING HANDS TO USE HANDHELD TELEPHONE W...,GEORGIA AVE@ PRICE AVE,39.036513,-77.050175,False,...,BLACK,F,SILVER SPRING,MD,MD,B - Unmarked Patrol,"(39.0365133333333, -77.050175)",2024-11-26 10:47:00,GEORGIA AVE/ PRICE AVE,DISTRACTED_DRIVING
1048477,9ffbeaac-2d8e-4502-829c-bf01f40654bd,2016-05-05,11:13:00,MCP,"4th District, Wheaton",PEDESTRIAN CROSSING ROADWAY BETWEEN ADJACENT I...,GEORGIA AVE AND CONNECTICUT AVE,39.082222,-77.076370,False,...,HISPANIC,F,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0822216666667, -77.07637)",2016-05-05 11:13:00,GEORGIA AVE / CONNECTICUT AVE,OTHER
1768986,4ca13b23-3736-4b59-8185-21543b22ce93,2022-04-25,19:36:00,MCP,"3rd District, Silver Spring",DISPLAYING EXPIRED REGISTRATION PLATE ISSUED B...,CHERRY HILL RD @ PLUM ORCHARD DR,39.053794,-76.953392,False,...,BLACK,M,BLADENSBURG,MD,MD,A - Marked Patrol,"(39.053794, -76.9533923333333)",2022-04-25 19:36:00,CHERRY HILL RD / PLUM ORCHARD DR,REGISTRATION
799339,c0973f32-b6f9-43b0-a2c7-8d7471df6913,2013-02-14,07:20:00,MCP,"3rd District, Silver Spring",PEDESTRIAN FAILURE TO YIELD RIGHT-OF-WAY TO VE...,UNIVERSITY BLVD @ EAST MELBOURNE AVE,38.997552,-77.109710,True,...,BLACK,F,SILVER SPRING,MD,VA,A - Marked Patrol,"(38.9975516666667, -77.10971)",2013-02-14 07:20:00,UNIVERSITY BLVD / EAST MELBOURNE AVE,OTHER
962366,9eb7919d-5818-4b22-8c6d-a9c4cd440774,2018-01-03,07:35:00,MCP,"2nd District, Bethesda",PEDESTRIAN CROSSING ROADWAY BETWEEN ADJACENT I...,355/SOUTH DR,38.998609,-77.096700,False,...,BLACK,M,WASHINGTON,DC,DC,A - Marked Patrol,"(38.9986093333333, -77.0967005)",2018-01-03 07:35:00,355/SOUTH DR,OTHER
1357172,15d2e317-6281-4157-a560-3a9aa6dec6ca,2020-01-28,07:30:00,MCP,"4th District, Wheaton","PEDESTRIAN FAIL TO OBEY ""UPRAISED HAND"" SIGNAL",REDDIE/FERN,39.038858,-77.049470,False,...,WHITE,M,BROOKLYN,NY,NY,A - Marked Patrol,"(39.0388583333333, -77.04947)",2020-01-28 07:30:00,REDDIE/FERN,OTHER
1953855,5a0f9722-bfd2-475f-8d54-803fbdfb5acd,2024-10-05,19:10:00,MCP,Headquarters and Special Operations,DRIVING VEH. WHILE IMPAIRED BY ALCOHOL,RIDGE RD/ GUE RD,39.287951,-76.626341,False,...,WHITE,M,GAITHERSBURG,MD,MD,B - Unmarked Patrol,"(39.287951, -76.6263408333333)",2024-10-05 19:10:00,RIDGE RD/ GUE RD,OTHER
1603954,7e6d1f73-bda7-4862-8605-fe548e5ed7d6,2019-03-13,15:20:00,MCP,"4th District, Wheaton",PEDESTRIAN CROSSING ROADWAY BETWEEN ADJACENT I...,LAYHILL RD @ GEORGIA AVE,39.061087,-77.051220,False,...,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(39.0610866666667, -77.05122)",2019-03-13 15:20:00,LAYHILL RD / GEORGIA AVE,OTHER
67415,25863f25-c84b-460e-b885-8f98e9a379d1,2024-02-07,15:55:00,MCP,Headquarters and Special Operations,IND. OPERATING MOTOR SCOOTER W/O WEARING REQU...,GEORGIA AVE AND UNIVERSITY BLVD,39.041823,-77.052224,False,...,HISPANIC,M,MTRAINER,MD,MD,A - Marked Patrol,"(39.0418233333333, -77.052224)",2024-02-07 15:55:00,GEORGIA AVE / UNIVERSITY BLVD,OTHER
960398,af3de719-4fd5-4187-80b8-78d38ada22bc,2015-01-16,11:15:00,MCP,"2nd District, Bethesda",PEDESTRIAN FAILURE TO WALK ON RIGHT HALF CROSS...,WISCONSIN AVE AT EAST WEST HWY,38.984570,-77.093890,False,...,OTHER,M,OLNEY,MD,MD,B - Unmarked Patrol,"(38.98457, -77.09389)",2015-01-16 11:15:00,WISCONSIN AVE / EAST WEST HWY,OTHER
131961,f681791c-fd56-4544-b91f-5fbaa6c64bee,2018-04-15,21:54:00,MCP,"3rd District, Silver Spring",FAILURE TO SECURELY FASTEN REGISTRATION PLATE ...,10986 NEW HAMPSHIRE AVE,39.035597,-76.988612,False,...,BLACK,F,BOWIE,MD,XX,A - Marked Patrol,"(39.0355966666667, -76.9886116666667)",2018-04-15 21:54:00,10986 NEW HAMPSHIRE AVE,REGISTRATION
435681,af57e9f6-8a02-44e0-840d-ade7097149f5,2015-02-01,08:31:00,MCP,"4th District, Wheaton","PEDESTRIAN FAIL TO OBEY DONT WALK"", ""UPRAISED ...",GEORGIA AVE /PRICHARD DR,38.997722,-77.109737,False,...,HISPANIC,M,SILVER SPRING,MD,MD,A - Marked Patrol,"(38.9977216666667, -77.1097366666667)",2015-02-01 08:31:00,GEORGIA AVE /PRICHARD DR,OTHER

In [89]:
data['State'].isnull().sum()

54

In [90]:
data.loc[
    data["State"].isna(),
    ["State", "Driver State", "DL State"]
]

        State Driver State DL State
107647    NaN           MD       MD
114943    NaN           MD       MD
115970    NaN           DC       DC
131922    NaN           MD       MD
134577    NaN           MD       MD
142540    NaN           MD       MD
167196    NaN           MD       MD
176015    NaN           MD       MD
183165    NaN           MD       MD
187730    NaN           MD       MD
210375    NaN           MD       MD
214264    NaN           MD       MD
228861    NaN           MD       MD
235806    NaN           NJ       NJ
235983    NaN           DC       DC
237248    NaN           NJ       NJ
248998    NaN           MD       MD
256066    NaN           MD       MD
257416    NaN           NJ       NJ
257917    NaN           NJ       NJ
269708    NaN           VA       VA
281523    NaN           NJ       NJ
293303    NaN           NJ       NJ
293633    NaN           VA       VA
294026    NaN           MD       MD
299051    NaN           DC       DC
300282    NaN           MD       MD
304273    NaN           MD       MD
312549    NaN           NJ       NJ
312551    NaN           NJ       NJ
314991    NaN           MD       MD
317583    NaN           DC       DC
325261    NaN           DC       DC
330325    NaN           NJ       NJ
334773    NaN           MD       MD
342411    NaN           NJ       NJ
352678    NaN           MD       MD
353111    NaN           NJ       NJ
354706    NaN           NJ       NJ
357259    NaN           DC       DC
358637    NaN           DC       DC
427124    NaN           MD       MD
462685    NaN           MD       MD
921315    NaN           MD       MD
962172    NaN           MD       MD
995152    NaN           MD       MD
1012916   NaN           MD       MD
1198625   NaN           MD       MD
1221208   NaN           MD       MD
1275727   NaN           PA       PA
1339016   NaN           MD       MD
1366317   NaN           MD       MD
1406224   NaN           MD       MD
1406465   NaN           MD       MD

In [91]:
mask = (
    data['State'].isna() &
    (data['Driver State'] == data['DL State'])
)

In [92]:
data.loc[mask, 'State'] = data.loc[mask, 'Driver State']

In [93]:
data['State'].isnull().sum()

0

In [94]:
#  VehicleType
data['VehicleType'].value_counts()

VehicleType
02 - Automobile              1692400
05 - Light Duty Truck         101692
28 - Other                     33435
03 - Station Wagon             26589
01 - Motorcycle                17651
06 - Heavy Duty Truck          15308
29 - Unknown                   10411
08 - Recreational Vehicle       5063
19 - Moped                      2089
25 - Utility Trailer            1841
07 - Truck/Road Tractor         1708
20 - Commercial Rig             1082
04 - Limousine                   888
10 - Transit Bus                 649
12 - School Bus                  403
27 - Farm Equipment              134
29 - Other                       110
09 - Farm Vehicle                108
26 - Boat Trailer                 93
21 - Tandem Trailer               82
11 - Cross Country Bus            57
23 - Travel/Home Trailer          34
28 - Electric Bicycle             27
22 - Mobile Home                  26
24 - Camper                       23
18 - Police(Non-Emerg)            22
14 - Ambulance(Non-Emerg)         19
30 - Unknown                      19
13 - Ambulance(Emerg)             14
15 - Fire(Emerg)                  10
16 - Fire(Non-Emerg)               5
17 - Police(Emerg)                 5
18 - Police Vehicle                4
15 - Fire Vehicle                  3
14 - Ambulance                     2
13 - Ambulance                     1
Name: count, dtype: int64

In [95]:
vehicle_split = data['VehicleType'].str.split('-', n=1, expand=True) # n=1 split once at first occurance

In [96]:
vehicle_split

           0            1
1        02    Automobile
2        02    Automobile
3        02    Automobile
4        02    Automobile
5        02    Automobile
...      ...          ...
2070108  02    Automobile
2070109  02    Automobile
2070110  02    Automobile
2070113  02    Automobile
2070114  02    Automobile

[1912007 rows x 2 columns]

In [97]:
data['VehicleCode'] = vehicle_split[0].str.strip()
data['VehicleCategory'] = vehicle_split[1].str.strip()

In [98]:
data.drop(columns=['VehicleCode'], inplace = True)

In [99]:
# Year
data['Year'] = pd.to_numeric(data['Year'], errors = "coerce")

In [100]:
data.shape

(1912007, 47)

In [101]:
data = data[
    (data['Year'] >= 1960) &
    (data['Year'] <= 2025)
]

## Make Model and color

In [102]:
print(data['Make'].value_counts(dropna = False))
print(data['Make'].nunique())

Make
TOYOTA         221746
HONDA          208467
FORD           173259
TOYT           108508
NISSAN         100590
                ...
VOKLKSWAGON         1
KWORTH              1
LGCH                1
PRUIS               1
HONDRA              1
Name: count, Length: 4669, dtype: int64
4668

In [103]:
# Standardize:
data['Make'] = data['Make'].str.strip().str.upper()

In [104]:
data['Make'].value_counts(dropna = False)

Make
TOYOTA         221746
HONDA          208467
FORD           173259
TOYT           108508
NISSAN         100590
                ...
VOKLKSWAGON         1
KWORTH              1
LGCH                1
PRUIS               1
HONDRA              1
Name: count, Length: 4669, dtype: int64

In [105]:
mappings = {
    'TOYT':'TOYOTA',
    'HONDRA':'HONDA',
    'CHEV':'CHEVROLET',
    'LEXS':'LEXUS',
    'VOKLKSWAGON':'VOLKSWAGEN',
    'FORSCHE':'PORSCHE',
    'HOND':'HONDA',
    'HONDAA':'HONDA',
    'CHEVROLETROLETROLETROLETROLETROLET':'CHEVROLET'

}

In [106]:
data['Make'] = data['Make'].str.strip().replace(mappings)

In [107]:
data.loc[
    data['Make'].str.contains('TIY'),
    ['Make']
].value_counts()

Make
TIYITA    18
TIYT      17
TIYOTA     4
TIYOT      2
TIY        1
Name: count, dtype: int64

In [108]:
data.shape

(1899304, 47)

In [109]:
330254+283698+173259+100590+54446

942247

In [110]:
(942247/data.shape[0])*100

49.61012033881885

In [111]:
data['Make'].value_counts()

Make
TOYOTA       330254
HONDA        283707
FORD         173259
NISSAN       100590
CHEVROLET     94605
              ...
TIY               1
TOYYOT            1
KWORTH            1
LGCH              1
PRUIS             1
Name: count, Length: 4660, dtype: int64

In [112]:
make_counts = data['Make'].value_counts()

print((make_counts == 1).sum())
print((make_counts <= 5).sum())

1630
3313

In [113]:
rare_rows = make_counts[make_counts <= 5].sum()

print("Rows affected:", rare_rows)
print("Percentage:", rare_rows / len(data) * 100)

Rows affected: 6659
Percentage: 0.350602115301184

In [115]:
# Model:

data['Model'].value_counts()

Model
4S              185423
TK              115753
CIVIC            70055
ACCORD           69029
CAMRY            65733
                 ...
ENGX                 1
SANTAGE              1
QX50S                1
TRAC TRLR            1
PATHERFINDER         1
Name: count, Length: 22279, dtype: int64

In [116]:
data['Model'] = data['Model'].str.strip().str.upper()

In [118]:
# Color:
data["Color"].value_counts()

Color
BLACK          402126
SILVER         337658
WHITE          316201
GRAY           233820
RED            144900
BLUE           138729
GREEN           57397
GOLD            51683
BLUE, DARK      40667
TAN             33006
MAROON          31535
BLUE, LIGHT     23062
BEIGE           18515
GREEN, DK       17319
GREEN, LGT       9390
BROWN            7951
ORANGE           6662
YELLOW           6653
BRONZE           4217
PURPLE           3495
MULTICOLOR       1433
CREAM             996
COPPER            558
PINK              287
CHROME             44
CAMOUFLAGE         38
Name: count, dtype: int64

## Violation Type:

In [120]:
data['Violation Type'].value_counts(dropna = False)

Violation Type
Warning     1012691
Citation     800256
ESERO         85547
SERO            810
Name: count, dtype: int64

## Charge:

In [121]:
data['Charge'].value_counts(dropna = False)

Charge
21-801.1        270310
21-201(a1)      159797
13-409(b)        84990
21-707(a)        60365
13-401(h)        56910
                 ...
13-920(h2I)          1
11-395.8             1
21-1132(d1)          1
13-626(f)            1
11-393.11(8)         1
Name: count, Length: 1161, dtype: int64

In [126]:
data.columns

Index(['SeqID', 'Date Of Stop', 'Time Of Stop', 'Agency', 'SubAgency',
       'Description', 'Location', 'Latitude', 'Longitude', 'Accident', 'Belts',
       'Personal Injury', 'Property Damage', 'Fatal', 'Commercial License',
       'HAZMAT', 'Commercial Vehicle', 'Alcohol', 'Work Zone',
       'Search Conducted', 'Search Disposition', 'Search Outcome',
       'Search Reason', 'Search Reason For Stop', 'Search Type',
       'Search Arrest Reason', 'State', 'VehicleType', 'Year', 'Make', 'Model',
       'Color', 'Violation Type', 'Charge', 'Article',
       'Contributed To Accident', 'Race', 'Gender', 'Driver City',
       'Driver State', 'DL State', 'Arrest Type', 'Geolocation',
       'Stop_dateTime', 'Location_clean', 'Violation_category',
       'VehicleCategory'],
      dtype='str')

In [153]:
# To check row with same SEQIDs and different charges value:
print(data.groupby('SeqID')['Accident'].nunique().sort_values(ascending=False).head())

SeqID
186e3649-469b-475b-98b7-0d8e545976f5    2
6e2b705a-2901-4b30-98f9-8ab842c45b4c    2
58c68f62-8843-4c15-a954-8528604d421e    2
a543531c-7687-47e3-9bd5-3b0c26c486c8    2
8a74a863-35d3-48c6-842d-838c642d9a2a    2
Name: Accident, dtype: int64

In [141]:
data['SeqID'].value_counts().head()

SeqID
33c49de3-9e36-4f36-9326-b59a95e86fe8    59
6c64b741-3b7e-4658-9fed-fd5c3af27250    43
c474e98e-128c-40e0-a487-d988cc67f0bd    39
859768f4-bde0-427b-a60f-07b1e2aaadc4    39
8fe624e5-2bef-4cf9-963b-58fbb1e206c2    37
Name: count, dtype: int64

In [144]:
temp = data[data['SeqID'] == '33c49de3-9e36-4f36-9326-b59a95e86fe8']

In [157]:
temp.duplicated().sum()

0

In [146]:
temp.nunique(dropna = False)[temp.nunique(dropna=False) > 1]

Description                56
Accident                    2
Charge                     47
Contributed To Accident     2
Violation_category          5
dtype: int64

In [147]:
temp['SeqID'].nunique()

1

In [148]:
temp.shape

(59, 47)

In [158]:
data['Charge'].nunique()

1161

In [161]:
data['Charge'].value_counts().head(20)

Charge
21-801.1         270310
21-201(a1)       159797
13-409(b)         84990
21-707(a)         60365
13-401(h)         56910
13-411(f)         54844
16-112(c)         51443
21-1124.2(d2)     47207
21-801(a)         35712
13-411(d)         35649
16-303(c)         34915
16-303(h)         32631
64*               32114
16-101(a)         28771
22-412.3(b)       28033
21-309(b)         27256
21-901.1(b)       26752
13-411(a)         25714
22-201.1          25045
21-202(h1)        24297
Name: count, dtype: int64

In [174]:
data['Violation_category'].value_counts()

Violation_category
SPEEDING              338378
REGISTRATION          329486
TRAFFIC_CONTROL       256856
LICENSE               241577
VEHICLE_LIGHTING      135605
OTHER                 131209
TRAFFIC_SIGNAL         73379
DUI                    57664
DISTRACTED_DRIVING     53352
LANE_VIOLATION         52732
RECKLESS_DRIVING       39404
WINDOW_TINT            34476
SEAT_BELT              32451
INSURANCE              20461
RIGHT_OF_WAY           20181
TURNING_VIOLATION      18586
VEHICLE_EQUIPMENT      17672
PARKING                13836
ACCIDENT_RELATED       10094
FOLLOWING_DISTANCE      8846
PEDESTRIAN              8044
CHILD_SAFETY            5007
UNKNOWN                    8
Name: count, dtype: int64

In [175]:
(131209/data.shape[0])*100

6.90826744954994

In [170]:
other_descriptions = data.loc[data['Violation_category']=='OTHER','Description']
other_descriptions.value_counts().head(50)

Description
DRIVING VEH. W/O ADEQUATE REAR REG. PLATE ILLUMINATION                                                 19746
OPERATING UNREGISTERED MOTOR VEHICLE ON HIGHWAY                                                        13777
FAILURE TO DRIVE VEHICLE ON RIGHT HALF OF ROADWAY WHEN REQUIRED                                        13415
DRIVER WHEN TURNING LEFT FAIL TO YIELD RIGHT OF WAY TO VEHICLE APPROACHING FROM OPPOSITE DIRECTION      9140
HOLDER OF LEARNER'S PERMIT DRIVING W/O REQ. SUPERVISION                                                 8770
POSSESSING SUSPENDED LIC.                                                                               8023
DRIVER OF MOTOR VEHICLE FOLLOWING VEHICLE CLOSER THAN REASONABLE AND PRUDENT                            7668
DRIVING WHILE LIC. SUSP. UNDER 16-203, 16-206A2 FAIL TO ATTEND DIP, 17-106, 26-204/206, 27-103          7405
FAILURE TO DISPLAY TAB ON PLATES OF VEH. AS REQUIRED BY ADM.                                            6275
DRIVING ON HWY. WITH OBSTRUCTED WINDSHIELD VIEW                                                         5067
FAILURE OF MV OPER TO PRESENT EVIDENCE OF REQUIRED SECURITY ON REQUEST OF A LAW ENFORCEMENT OFFICER     4569
DRIVER FAIL TO STOP AT STEADY RED ARROW SIGNAL                                                          4426
FAILURE VEH. TO YIELD INTERSECTION RIGHT-OF-WAY TO ANOTHER VEH.                                         4414
FAILURE TO ATTACH VEH. REG. PLATES AT FRONT AND REAR                                                    4341
DRIVER FAILING TO GIVE TURN SIGNAL CONTINUOUSLY DURING LAST 100' OF TRAVEL BEFORE TURNING               4250
DISPLAY SUSPENDED LIC.                                                                                  3480
DRIVING WRONG WAY--ONE WAY STREET                                                                       3116
FAILURE OF DRIVER TO DRIVE TO CURB UPON SIGNAL BY POLICE VEH.                                           3067
DRIVER FAIL TO MAKE REQUIRED STOP AT SIGN                                                               2983
RT. TURN FROM IMPROPER ROAD POSITION                                                                    2934
FAILURE OF VEH. DRIVER INVOLVED IN ACCIDENT TO GIVE INSURANCE POLICY INFORMATION                        2866
DRIVING A MOTOR VEH WITHOUT A VALID MEDICAL EXAMINERS CERTIFICATE IN POSSESSION                         2660
DRIVING UNSAFE VEH. ON HWY.                                                                             2600
OWNER FAILURE TO MAINTAIN REQUIRED SECURITY FOR VEH. DURING REG. PERIOD                                 2551
FAILURE TO NOTIFY ADM. OF ADDRESS CHANGE WITHIN 30 DAYS                                                 2383
GLASS (*)                                                                                               2324
FAILURE YIELD RIGHT OF WAY ON LEFT TURN                                                                 2250
DRIVER WRITING,SENDING,READING A TEXT,ELECTRONIC MSG. WHILE OPER. VEH. IN TRAVEL PORTION OF HWY         2231
LEFT TURN FROM IMPROPER ROAD POSITION                                                                   2118
DRIVING OFF ROADWAY WHILE PASSING VEHICLE                                                               2077
DISPLAYING REG. PLATE ISSUED FOR OTHER VEHICLE                                                          2072
DRIVING A VEHICLE WHILE A REMOVABLE WINDSHIELD PLACARD IS HANGING FROM THE INSIDE REARVIEW MIRROR       1935
HOLDER OF LEARNER'S PERMIT DRIVING WITH UN- AUTHORIZED PERSON OCCUPYING FRONT SEAT                      1889
CAUSING STANDING VEH. TO OBSTRUCT FREE VEH. PASSAGE OF ROADWAY                                          1852
DRIVING VEH. WHILE WEARING EARPHONES                                                                    1851
UNSAFE BACKING OF MOTOR VEH.                                                                            1810
DRIVER TURNING VEHICLE WITHOUT GIVING APPROPRIATE SIGNAL AS REQUIRED                                    1655
FAILURE TO DRIVE RIGHT OF CENTER                                                                        1653
FAILURE TO RETURN TO & REMAIN AT SCENE OF ACCIDENTINVOLVING ATTENDED VEH.DAMAGE                         1645
STOPPING VEH. ON CROSSWALK                                                                              1604
DRIVING MOTOR VEHICLE OFF ROADWAY WHILE PASSING VEHICLE                                                 1603
EXHAUST SYSTEM                                                                                          1296
FAILURE OF MV OPER. DRIVING ON HWY TO BE IN POSS.OF, CARRY IN MV EVID. OF REQ'D SECURITY FOR MV         1263
FAILURE TO STOP WHEN ENTERING HIGHWAY                                                                   1247
FOLLOWING VEH. TOO CLOSELY                                                                              1157
DRIVER MAKING IMPROPER TURN AT INTERSECTION                                                             1150
MOTOR VEH. EQUIPPED WITH UNLAWFULLY MODIFIED EXHAUST SYSTEM                                             1123
FAILURE TO STOP AFTER ACCIDENT INVOLVING DAMAGE TO ATTENDED VEH.                                        1049
AGGRESSIVE DRIVING                                                                                      1006
DRIVER SPINNING WHEELS                                                                                  1002
Name: count, dtype: int64

In [176]:
data['Charge'] = data['Charge'].astype(str).str.strip().str.upper()

## Article:

In [177]:
data['Article'].value_counts(dropna = False)

Article
Transportation Article    1794396
NaN                         86357
Maryland Rules              18464
BR                             56
TG                             19
1A                              9
00                              3
Name: count, dtype: int64

In [183]:
data.loc[
    data['Article'].isna(),
    ['Charge', 'Description']
].sample(20)

        Charge      Description
1851487     61      WINDOW TINT
1857747    55*   HEADLIGHTS (*)
1894668    64*      STOP LIGHTS
1889480     53   EXHAUST SYSTEM
1920593    64*  STOP LIGHTS (*)
91148      64*  STOP LIGHTS (*)
1869196    61*        GLASS (*)
1877540    88*    I.D. LAMP (*)
1929475     53   EXHAUST SYSTEM
1834083    64*  STOP LIGHTS (*)
1935049    56*   TAILLIGHTS (*)
1934598    64*  STOP LIGHTS (*)
88437      56*   TAILLIGHTS (*)
1819293    65*       TAG LIGHTS
1870245     61      WINDOW TINT
16866       61      WINDOW TINT
2061125    55*   HEADLIGHTS (*)
1876935    55*   HEADLIGHTS (*)
1930554    64*  STOP LIGHTS (*)
1832056    56*   TAILLIGHTS (*)

In [ ]:
data.loc[
    data['Charge'].isin(
        ['53','55*','56*','61','61*','64*','65*','88*']
    ),
    'Article'
].value_counts(dropna=False) # Most of these rules are Mary land rules

Article
NaN    79945
Name: count, dtype: int64

## Contributed To Accident

In [187]:
data['Contributed To Accident'].value_counts(dropna = False)

Contributed To Accident
False    1849527
True       49777
Name: count, dtype: int64

## Race

In [188]:
data['Race'].value_counts(dropna = False)

Race
WHITE              633044
BLACK              600507
HISPANIC           425647
OTHER              128904
ASIAN              107843
NATIVE AMERICAN      3359
Name: count, dtype: int64

## Gender:

In [189]:
data['Gender'].value_counts(dropna = False)

Gender
M    1275371
F     620685
U       3248
Name: count, dtype: int64

## Driver cities:

In [196]:
data['Driver City'].value_counts(dropna = False).head(50)

Driver City
SILVER SPRING         464274
GAITHERSBURG          202351
GERMANTOWN            161912
ROCKVILLE             154105
WASHINGTON             59545
MONTGOMERY VILLAGE     53772
BETHESDA               51450
HYATTSVILLE            42965
POTOMAC                37040
OLNEY                  30773
CLARKSBURG             27053
FREDERICK              26851
LAUREL                 26768
NORTH POTOMAC          20629
KENSINGTON             19559
TAKOMA PARK            19488
DAMASCUS               19410
BURTONSVILLE           17128
BELTSVILLE             16673
CHEVY CHASE            15721
BALTIMORE              14547
DERWOOD                13511
BOYDS                  12609
COLUMBIA               12177
BOWIE                  11140
POOLESVILLE            10105
BROOKEVILLE             9643
WHEATON                 9349
ADELPHI                 8860
UPPER MARLBORO          8494
ALEXANDRIA              8273
LANHAM                  8160
MOUNT AIRY              7247
GREENBELT               5986
RIVERDALE               5576
COLLEGE PARK            5483
ARLINGTON               5277
HAGERSTOWN              5087
ELLICOTT CITY           4888
NORTH BETHESDA          3907
WOODBRIDGE              3828
DARNESTOWN              3696
CAPITOL HEIGHTS         3493
FALLS CHURCH            3444
FORT WASHINGTON         3245
FAIRFAX                 3234
LAYTONSVILLE            3170
WALDORF                 3167
CLINTON                 3059
NEW CARROLLTON          3041
Name: count, dtype: int64

## Driver State

In [197]:
data['Driver State'].value_counts(dropna = False)

Driver State
MD     1717709
DC       61779
VA       57752
PA        9397
FL        6650
        ...
NaN          5
SK           4
PE           2
PQ           1
NS           1
Name: count, Length: 68, dtype: int64

In [198]:
data['Driver State'] = data['Driver State'].str.strip().str.upper()

## DL State:

In [199]:
data['DL State'].value_counts(dropna=False)

DL State
MD    1658904
DC      62773
VA      61501
XX      25534
PA      11085
       ...
PQ          6
MH          5
NS          5
NU          3
NF          2
Name: count, Length: 73, dtype: int64

## Arrest Type:

In [200]:
data['Arrest Type'].value_counts(dropna = False)

Arrest Type
A - Marked Patrol                         1511232
Q - Marked Laser                           189905
B - Unmarked Patrol                         88990
L - Motorcycle                              19878
G - Marked Moving Radar (Stationary)        19249
S - License Plate Recognition               15748
E - Marked Stationary Radar                 15525
O - Foot Patrol                             12595
R - Unmarked Laser                          10958
M - Marked (Off-Duty)                        5105
I - Marked Moving Radar (Moving)             4146
H - Unmarked Moving Radar (Stationary)       2508
F - Unmarked Stationary Radar                1026
J - Unmarked Moving Radar (Moving)            954
C - Marked VASCAR                             499
P - Mounted Patrol                            348
D - Unmarked VASCAR                           307
N - Unmarked (Off-Duty)                       278
K - Aircraft Assist                            53
Name: count, dtype: int64

In [201]:
split_arrestType = data['Arrest Type'].str.split('-',n=1,expand=True)

In [202]:
split_arrestType.head()

    0               1
1  A    Marked Patrol
2  A    Marked Patrol
3  A    Marked Patrol
4  A    Marked Patrol
5  A    Marked Patrol

In [203]:
data['ArrestTypeCategory'] = split_arrestType[1].str.strip()

## Geo Location:

In [204]:
data[['Latitude','Longitude','Geolocation']].sample(10)

          Latitude  Longitude                            Geolocation
2029354  39.228786 -77.289671  (39.2287863333333, -77.2896713333333)
1529804  39.100187 -76.935352  (39.1001866666667, -76.9353516666667)
1880390  39.168290 -77.153937          (39.16829, -77.1539366666667)
148756   39.058990 -77.047395  (39.0589901666667, -77.0473953333333)
1990122  39.168547 -77.170946  (39.1685468333333, -77.1709461666667)
1114531  39.099240 -77.100078          (39.09924, -77.1000783333333)
397178   39.070045 -77.076048         (39.070045, -77.0760483333333)
1016351  39.153510 -77.212918          (39.15351, -77.2129183333333)
788940   39.246602 -77.119717  (39.2466016666667, -77.1197166666667)
666600   39.115137 -77.121802  (39.1151366666667, -77.1218016666667)

In [205]:
data.loc[
    data['Latitude'].isna() |
    data['Longitude'].isna(),
    'Geolocation'
].notna().sum()

0

In [206]:
data.drop(columns=['Geolocation'], inplace=True)

In [211]:
data.columns

Index(['SeqID', 'Date Of Stop', 'Time Of Stop', 'Agency', 'SubAgency',
       'Description', 'Location', 'Latitude', 'Longitude', 'Accident', 'Belts',
       'Personal Injury', 'Property Damage', 'Fatal', 'Commercial License',
       'HAZMAT', 'Commercial Vehicle', 'Alcohol', 'Work Zone',
       'Search Conducted', 'Search Disposition', 'Search Outcome',
       'Search Reason', 'Search Reason For Stop', 'Search Type',
       'Search Arrest Reason', 'State', 'VehicleType', 'Year', 'Make', 'Model',
       'Color', 'Violation Type', 'Charge', 'Article',
       'Contributed To Accident', 'Race', 'Gender', 'Driver City',
       'Driver State', 'DL State', 'Arrest Type', 'Stop_dateTime',
       'Location_clean', 'Violation_category', 'VehicleCategory',
       'ArrestTypeCategory', 'Month', 'Weekday', 'Hour', 'TimeOfDay'],
      dtype='str')

In [209]:
# Month
data['Month'] = data['Stop_dateTime'].dt.month_name()

# Weekday
data['Weekday'] = data['Stop_dateTime'].dt.day_name()

# Hour
data['Hour'] = data['Stop_dateTime'].dt.hour

In [210]:
def time_of_day(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'

data['TimeOfDay'] = data['Hour'].apply(time_of_day)

In [214]:
final_columns = [
    # Identifiers
    'SeqID',

    # Time
    'Stop_dateTime',
    'Month',
    'Weekday',
    'Hour',
    'TimeOfDay',

    # Violation Information
    'Description',
    'Violation_category',
    'Violation Type',
    'Charge',

    # Geography
    'Location_clean',
    'Latitude',
    'Longitude',
    'State',

    # Driver Demographics
    'Race',
    'Gender',
    'Driver City',
    'Driver State',
    'DL State',

    # Vehicle Information
    'VehicleCategory',
    'VehicleType',
    'Make',
    'Model',
    'Year',
    'Color',

    # Incident Information
    'Accident',
    'Personal Injury',
    'Property Damage',
    'Fatal',
    'Contributed To Accident',

    # Context
    'Alcohol',
    'Belts',
    'Work Zone',

    # Search Information
    'Search Conducted',

    # Arrest Information
    'Arrest Type',
    'ArrestTypeCategory'
]

In [216]:
final_df = data[final_columns]

In [217]:
print(final_df.shape)
print(final_df.columns.tolist())

(1899304, 36)
['SeqID', 'Stop_dateTime', 'Month', 'Weekday', 'Hour', 'TimeOfDay', 'Description', 'Violation_category', 'Violation Type', 'Charge', 'Location_clean', 'Latitude', 'Longitude', 'State', 'Race', 'Gender', 'Driver City', 'Driver State', 'DL State', 'VehicleCategory', 'VehicleType', 'Make', 'Model', 'Year', 'Color', 'Accident', 'Personal Injury', 'Property Damage', 'Fatal', 'Contributed To Accident', 'Alcohol', 'Belts', 'Work Zone', 'Search Conducted', 'Arrest Type', 'ArrestTypeCategory']

In [219]:
final_df.to_csv(
    r"D:\dataset\traffic_violations_cleaned.csv",
    index=False
)